### ISSUE TITLE
logstash input sqlserver ouput kafka failed

### ISSUE THREAD

**Issue by v0yager** [logstash-plugins/logstash-output-kafka#192]
I want to get the sqlserver data into kafka.
But I got an error when I start logstash with config file.
Thanks a lot~~
- Version:logstash-6.2.4
- Operating System: windows server 2012 R2
- Config File (if you have sensitive info, please remove it):
input{
	jdbc{
		jdbc_driver_library => "D:\sqljdbc_6.4\chs\mssql-jdbc-6.4.0.jre7.jar"
		jdbc_driver_class =>"com.microsoft.sqlserver.jdbc.SQLServerDriver"
		jdbc_connection_string => "jdbc:sqlserver://ip:port;databasename=xxxxx"
		jdbc_user => "XXXX"
		jdbc_password => "XXXX"
		statement => "SELECT TOP 1000 [AutoID]
      ,[CatalogID]
      ,[ItemID]
      ,[Type]
      ,[Name]
      ,[Description]
      ,[Attributes]
      ,[CustomColumn0]
      ,[CustomColumn1]
      ,[CustomColumn2]
      ,[CustomColumn3]
      ,[Owner]
      ,[LastModifier]
      ,[ModificationTime]
      ,[XML]
      ,[Revision]
  FROM XXXXXX"
		}
	}
#filter {
	
#}

output {
	stdout { codec => rubydebug }
	kafka {
		bootstrap_servers => "xxxx:9092"
		topic_id => "sqlserver-to-es"
		codec => "json"
		compression_type => "snappy"
		acks => "1"
		retries => "5"
	}
}

- log:
[2018-06-13T14:49:27,693][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>63, "stalling_thread_info"=>{"other"=>[{"thread_id"=>30, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-output-kafka-7.0.10/lib/logstash/outputs/kafka.rb:253:in `block in retrying_send'"}, {"thread_id"=>31, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-output-kafka-7.0.10/lib/logstash/outputs/kafka.rb:253:in `block in retrying_send'"}, {"thread_id"=>32, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-output-kafka-7.0.10/lib/logstash/outputs/kafka.rb:253:in `block in retrying_send'"}, {"thread_id"=>33, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-output-kafka-7.0.10/lib/logstash/outputs/kafka.rb:253:in `block in retrying_send'"}]}}

**Comment by jakelandis** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
