### ISSUE TITLE
2.0 version can't failover.

### ISSUE THREAD

**Issue by woshihaoren** [logstash-plugins/logstash-output-kafka#34]
Hi:
   I try test logstash-2.1.0 with logstash-output-kafka 2.0.0 to kafka9.0 failover.

    bootstrap_servers => "172.16.2.91:9092,172.16.2.91:9093"
   When I kill 172.16.2.91:9092,Then logstash stdout:
log4j, [2015-12-13T16:43:12.487]  WARN: org.apache.kafka.common.network.Selector: Error in I/O with /172.16.2.91
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:248)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)
log4j, [2015-12-13T16:43:12.487]  WARN: org.apache.kafka.common.network.Selector: Error in I/O with /172.16.2.91
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:248)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)
log4j, [2015-12-13T16:43:12.487]  WARN: org.apache.kafka.common.network.Selector: Error in I/O with /172.16.2.91
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:248)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)
log4j, [2015-12-13T16:43:12.493]  WARN: org.apache.kafka.common.network.Selector: Error in I/O with /172.16.2.91
java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:248)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)
log4j, [2015-12-13T16:43:12.494]  WARN: org.apache.kafka.common.network.Selector: Error in I/O with /172.16.2.91
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:238)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)

But,logstash1.5.4 with output kafka1.0 ,It can failover success.

    broker_list => "172.16.2.91:9092,172.16.2.91:9093"

**Comment by woshihaoren** [comment]
@suyograo @ph @karmi

**Comment by joekiller** [comment]
These are all warnings. Do the logs stop flowing?

**Comment by woshihaoren** [comment]
Yeah,I test again, you are right,just warning logs.
Maybe can stop flowing or just print one, because collect one log ,print one warn,log size is very big.

**Comment by joekiller** [comment]
It's controlled by log4j. We should probably provide some instructions for
customizing the log4j.properties file.

**Comment by joekiller** [comment]
@woshihaoren I'm going to close this because we don't have control over how kafka issues messages beyond log4j.properties manipulation which is beyond the scope of the immediate project.
